<?php
/**
 * ChannelAuditDetailsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * YouTube Data
 *
 * Supports core YouTube features, such as uploading videos, creating and managing playlists, searching for content, and much more.
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ChannelAuditDetailsTest Class Doc Comment
 *
 * @category    Class
 * @description The auditDetails object encapsulates channel data that is relevant for YouTube Partners during the audit process.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ChannelAuditDetailsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ChannelAuditDetails"
     */
    public function testChannelAuditDetails()
    {
    }

    /**
     * Test attribute "community_guidelines_good_standing"
     */
    public function testPropertyCommunityGuidelinesGoodStanding()
    {
    }

    /**
     * Test attribute "content_id_claims_good_standing"
     */
    public function testPropertyContentIdClaimsGoodStanding()
    {
    }

    /**
     * Test attribute "copyright_strikes_good_standing"
     */
    public function testPropertyCopyrightStrikesGoodStanding()
    {
    }

    /**
     * Test attribute "overall_good_standing"
     */
    public function testPropertyOverallGoodStanding()
    {
    }
}
