<?php
/**
 * ChannelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * YouTube Data
 *
 * Supports core YouTube features, such as uploading videos, creating and managing playlists, searching for content, and much more.
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ChannelTest Class Doc Comment
 *
 * @category    Class
 * @description A channel resource contains information about a YouTube channel.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ChannelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Channel"
     */
    public function testChannel()
    {
    }

    /**
     * Test attribute "audit_details"
     */
    public function testPropertyAuditDetails()
    {
    }

    /**
     * Test attribute "branding_settings"
     */
    public function testPropertyBrandingSettings()
    {
    }

    /**
     * Test attribute "content_details"
     */
    public function testPropertyContentDetails()
    {
    }

    /**
     * Test attribute "content_owner_details"
     */
    public function testPropertyContentOwnerDetails()
    {
    }

    /**
     * Test attribute "conversion_pings"
     */
    public function testPropertyConversionPings()
    {
    }

    /**
     * Test attribute "etag"
     */
    public function testPropertyEtag()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "invideo_promotion"
     */
    public function testPropertyInvideoPromotion()
    {
    }

    /**
     * Test attribute "kind"
     */
    public function testPropertyKind()
    {
    }

    /**
     * Test attribute "localizations"
     */
    public function testPropertyLocalizations()
    {
    }

    /**
     * Test attribute "snippet"
     */
    public function testPropertySnippet()
    {
    }

    /**
     * Test attribute "statistics"
     */
    public function testPropertyStatistics()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "topic_details"
     */
    public function testPropertyTopicDetails()
    {
    }
}
