<?php
/**
 * CommentListResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * YouTube Data
 *
 * Supports core YouTube features, such as uploading videos, creating and managing playlists, searching for content, and much more.
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CommentListResponseTest Class Doc Comment
 *
 * @category    Class
 * @description CommentListResponse
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CommentListResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CommentListResponse"
     */
    public function testCommentListResponse()
    {
    }

    /**
     * Test attribute "etag"
     */
    public function testPropertyEtag()
    {
    }

    /**
     * Test attribute "event_id"
     */
    public function testPropertyEventId()
    {
    }

    /**
     * Test attribute "items"
     */
    public function testPropertyItems()
    {
    }

    /**
     * Test attribute "kind"
     */
    public function testPropertyKind()
    {
    }

    /**
     * Test attribute "next_page_token"
     */
    public function testPropertyNextPageToken()
    {
    }

    /**
     * Test attribute "page_info"
     */
    public function testPropertyPageInfo()
    {
    }

    /**
     * Test attribute "token_pagination"
     */
    public function testPropertyTokenPagination()
    {
    }

    /**
     * Test attribute "visitor_id"
     */
    public function testPropertyVisitorId()
    {
    }
}
