<?php
/**
 * ContentRatingTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * YouTube Data
 *
 * Supports core YouTube features, such as uploading videos, creating and managing playlists, searching for content, and much more.
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ContentRatingTest Class Doc Comment
 *
 * @category    Class
 * @description Ratings schemes. The country-specific ratings are mostly for movies and shows. NEXT_ID: 71
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ContentRatingTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ContentRating"
     */
    public function testContentRating()
    {
    }

    /**
     * Test attribute "acb_rating"
     */
    public function testPropertyAcbRating()
    {
    }

    /**
     * Test attribute "agcom_rating"
     */
    public function testPropertyAgcomRating()
    {
    }

    /**
     * Test attribute "anatel_rating"
     */
    public function testPropertyAnatelRating()
    {
    }

    /**
     * Test attribute "bbfc_rating"
     */
    public function testPropertyBbfcRating()
    {
    }

    /**
     * Test attribute "bfvc_rating"
     */
    public function testPropertyBfvcRating()
    {
    }

    /**
     * Test attribute "bmukk_rating"
     */
    public function testPropertyBmukkRating()
    {
    }

    /**
     * Test attribute "catv_rating"
     */
    public function testPropertyCatvRating()
    {
    }

    /**
     * Test attribute "catvfr_rating"
     */
    public function testPropertyCatvfrRating()
    {
    }

    /**
     * Test attribute "cbfc_rating"
     */
    public function testPropertyCbfcRating()
    {
    }

    /**
     * Test attribute "ccc_rating"
     */
    public function testPropertyCccRating()
    {
    }

    /**
     * Test attribute "cce_rating"
     */
    public function testPropertyCceRating()
    {
    }

    /**
     * Test attribute "chfilm_rating"
     */
    public function testPropertyChfilmRating()
    {
    }

    /**
     * Test attribute "chvrs_rating"
     */
    public function testPropertyChvrsRating()
    {
    }

    /**
     * Test attribute "cicf_rating"
     */
    public function testPropertyCicfRating()
    {
    }

    /**
     * Test attribute "cna_rating"
     */
    public function testPropertyCnaRating()
    {
    }

    /**
     * Test attribute "cnc_rating"
     */
    public function testPropertyCncRating()
    {
    }

    /**
     * Test attribute "csa_rating"
     */
    public function testPropertyCsaRating()
    {
    }

    /**
     * Test attribute "cscf_rating"
     */
    public function testPropertyCscfRating()
    {
    }

    /**
     * Test attribute "czfilm_rating"
     */
    public function testPropertyCzfilmRating()
    {
    }

    /**
     * Test attribute "djctq_rating"
     */
    public function testPropertyDjctqRating()
    {
    }

    /**
     * Test attribute "djctq_rating_reasons"
     */
    public function testPropertyDjctqRatingReasons()
    {
    }

    /**
     * Test attribute "ecbmct_rating"
     */
    public function testPropertyEcbmctRating()
    {
    }

    /**
     * Test attribute "eefilm_rating"
     */
    public function testPropertyEefilmRating()
    {
    }

    /**
     * Test attribute "egfilm_rating"
     */
    public function testPropertyEgfilmRating()
    {
    }

    /**
     * Test attribute "eirin_rating"
     */
    public function testPropertyEirinRating()
    {
    }

    /**
     * Test attribute "fcbm_rating"
     */
    public function testPropertyFcbmRating()
    {
    }

    /**
     * Test attribute "fco_rating"
     */
    public function testPropertyFcoRating()
    {
    }

    /**
     * Test attribute "fmoc_rating"
     */
    public function testPropertyFmocRating()
    {
    }

    /**
     * Test attribute "fpb_rating"
     */
    public function testPropertyFpbRating()
    {
    }

    /**
     * Test attribute "fpb_rating_reasons"
     */
    public function testPropertyFpbRatingReasons()
    {
    }

    /**
     * Test attribute "fsk_rating"
     */
    public function testPropertyFskRating()
    {
    }

    /**
     * Test attribute "grfilm_rating"
     */
    public function testPropertyGrfilmRating()
    {
    }

    /**
     * Test attribute "icaa_rating"
     */
    public function testPropertyIcaaRating()
    {
    }

    /**
     * Test attribute "ifco_rating"
     */
    public function testPropertyIfcoRating()
    {
    }

    /**
     * Test attribute "ilfilm_rating"
     */
    public function testPropertyIlfilmRating()
    {
    }

    /**
     * Test attribute "incaa_rating"
     */
    public function testPropertyIncaaRating()
    {
    }

    /**
     * Test attribute "kfcb_rating"
     */
    public function testPropertyKfcbRating()
    {
    }

    /**
     * Test attribute "kijkwijzer_rating"
     */
    public function testPropertyKijkwijzerRating()
    {
    }

    /**
     * Test attribute "kmrb_rating"
     */
    public function testPropertyKmrbRating()
    {
    }

    /**
     * Test attribute "lsf_rating"
     */
    public function testPropertyLsfRating()
    {
    }

    /**
     * Test attribute "mccaa_rating"
     */
    public function testPropertyMccaaRating()
    {
    }

    /**
     * Test attribute "mccyp_rating"
     */
    public function testPropertyMccypRating()
    {
    }

    /**
     * Test attribute "mcst_rating"
     */
    public function testPropertyMcstRating()
    {
    }

    /**
     * Test attribute "mda_rating"
     */
    public function testPropertyMdaRating()
    {
    }

    /**
     * Test attribute "medietilsynet_rating"
     */
    public function testPropertyMedietilsynetRating()
    {
    }

    /**
     * Test attribute "meku_rating"
     */
    public function testPropertyMekuRating()
    {
    }

    /**
     * Test attribute "mena_mpaa_rating"
     */
    public function testPropertyMenaMpaaRating()
    {
    }

    /**
     * Test attribute "mibac_rating"
     */
    public function testPropertyMibacRating()
    {
    }

    /**
     * Test attribute "moc_rating"
     */
    public function testPropertyMocRating()
    {
    }

    /**
     * Test attribute "moctw_rating"
     */
    public function testPropertyMoctwRating()
    {
    }

    /**
     * Test attribute "mpaa_rating"
     */
    public function testPropertyMpaaRating()
    {
    }

    /**
     * Test attribute "mpaat_rating"
     */
    public function testPropertyMpaatRating()
    {
    }

    /**
     * Test attribute "mtrcb_rating"
     */
    public function testPropertyMtrcbRating()
    {
    }

    /**
     * Test attribute "nbc_rating"
     */
    public function testPropertyNbcRating()
    {
    }

    /**
     * Test attribute "nbcpl_rating"
     */
    public function testPropertyNbcplRating()
    {
    }

    /**
     * Test attribute "nfrc_rating"
     */
    public function testPropertyNfrcRating()
    {
    }

    /**
     * Test attribute "nfvcb_rating"
     */
    public function testPropertyNfvcbRating()
    {
    }

    /**
     * Test attribute "nkclv_rating"
     */
    public function testPropertyNkclvRating()
    {
    }

    /**
     * Test attribute "oflc_rating"
     */
    public function testPropertyOflcRating()
    {
    }

    /**
     * Test attribute "pefilm_rating"
     */
    public function testPropertyPefilmRating()
    {
    }

    /**
     * Test attribute "rcnof_rating"
     */
    public function testPropertyRcnofRating()
    {
    }

    /**
     * Test attribute "resorteviolencia_rating"
     */
    public function testPropertyResorteviolenciaRating()
    {
    }

    /**
     * Test attribute "rtc_rating"
     */
    public function testPropertyRtcRating()
    {
    }

    /**
     * Test attribute "rte_rating"
     */
    public function testPropertyRteRating()
    {
    }

    /**
     * Test attribute "russia_rating"
     */
    public function testPropertyRussiaRating()
    {
    }

    /**
     * Test attribute "skfilm_rating"
     */
    public function testPropertySkfilmRating()
    {
    }

    /**
     * Test attribute "smais_rating"
     */
    public function testPropertySmaisRating()
    {
    }

    /**
     * Test attribute "smsa_rating"
     */
    public function testPropertySmsaRating()
    {
    }

    /**
     * Test attribute "tvpg_rating"
     */
    public function testPropertyTvpgRating()
    {
    }

    /**
     * Test attribute "yt_rating"
     */
    public function testPropertyYtRating()
    {
    }
}
