<?php
/**
 * LiveBroadcastStatusTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * YouTube Data
 *
 * Supports core YouTube features, such as uploading videos, creating and managing playlists, searching for content, and much more.
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * LiveBroadcastStatusTest Class Doc Comment
 *
 * @category    Class
 * @description LiveBroadcastStatus
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LiveBroadcastStatusTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "LiveBroadcastStatus"
     */
    public function testLiveBroadcastStatus()
    {
    }

    /**
     * Test attribute "life_cycle_status"
     */
    public function testPropertyLifeCycleStatus()
    {
    }

    /**
     * Test attribute "live_broadcast_priority"
     */
    public function testPropertyLiveBroadcastPriority()
    {
    }

    /**
     * Test attribute "privacy_status"
     */
    public function testPropertyPrivacyStatus()
    {
    }

    /**
     * Test attribute "recording_status"
     */
    public function testPropertyRecordingStatus()
    {
    }
}
