<?php
/**
 * LiveChatSuperChatDetailsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * YouTube Data
 *
 * Supports core YouTube features, such as uploading videos, creating and managing playlists, searching for content, and much more.
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * LiveChatSuperChatDetailsTest Class Doc Comment
 *
 * @category    Class
 * @description LiveChatSuperChatDetails
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LiveChatSuperChatDetailsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "LiveChatSuperChatDetails"
     */
    public function testLiveChatSuperChatDetails()
    {
    }

    /**
     * Test attribute "amount_display_string"
     */
    public function testPropertyAmountDisplayString()
    {
    }

    /**
     * Test attribute "amount_micros"
     */
    public function testPropertyAmountMicros()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "tier"
     */
    public function testPropertyTier()
    {
    }

    /**
     * Test attribute "user_comment"
     */
    public function testPropertyUserComment()
    {
    }
}
