<?php
/**
 * LiveBroadcastContentDetailsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * YouTube Data
 *
 * Supports core YouTube features, such as uploading videos, creating and managing playlists, searching for content, and much more.
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * LiveBroadcastContentDetailsTest Class Doc Comment
 *
 * @category    Class
 * @description Detailed settings of a broadcast.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LiveBroadcastContentDetailsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "LiveBroadcastContentDetails"
     */
    public function testLiveBroadcastContentDetails()
    {
    }

    /**
     * Test attribute "bound_stream_id"
     */
    public function testPropertyBoundStreamId()
    {
    }

    /**
     * Test attribute "bound_stream_last_update_time_ms"
     */
    public function testPropertyBoundStreamLastUpdateTimeMs()
    {
    }

    /**
     * Test attribute "closed_captions_type"
     */
    public function testPropertyClosedCaptionsType()
    {
    }

    /**
     * Test attribute "enable_auto_start"
     */
    public function testPropertyEnableAutoStart()
    {
    }

    /**
     * Test attribute "enable_closed_captions"
     */
    public function testPropertyEnableClosedCaptions()
    {
    }

    /**
     * Test attribute "enable_content_encryption"
     */
    public function testPropertyEnableContentEncryption()
    {
    }

    /**
     * Test attribute "enable_dvr"
     */
    public function testPropertyEnableDvr()
    {
    }

    /**
     * Test attribute "enable_embed"
     */
    public function testPropertyEnableEmbed()
    {
    }

    /**
     * Test attribute "enable_low_latency"
     */
    public function testPropertyEnableLowLatency()
    {
    }

    /**
     * Test attribute "latency_preference"
     */
    public function testPropertyLatencyPreference()
    {
    }

    /**
     * Test attribute "mesh"
     */
    public function testPropertyMesh()
    {
    }

    /**
     * Test attribute "monitor_stream"
     */
    public function testPropertyMonitorStream()
    {
    }

    /**
     * Test attribute "projection"
     */
    public function testPropertyProjection()
    {
    }

    /**
     * Test attribute "record_from_start"
     */
    public function testPropertyRecordFromStart()
    {
    }

    /**
     * Test attribute "start_with_slate"
     */
    public function testPropertyStartWithSlate()
    {
    }
}
