<?php
/**
 * VideoSuggestionsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * YouTube Data
 *
 * Supports core YouTube features, such as uploading videos, creating and managing playlists, searching for content, and much more.
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * VideoSuggestionsTest Class Doc Comment
 *
 * @category    Class
 * @description Specifies suggestions on how to improve video content, including encoding hints, tag suggestions, and editor suggestions.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class VideoSuggestionsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "VideoSuggestions"
     */
    public function testVideoSuggestions()
    {
    }

    /**
     * Test attribute "editor_suggestions"
     */
    public function testPropertyEditorSuggestions()
    {
    }

    /**
     * Test attribute "processing_errors"
     */
    public function testPropertyProcessingErrors()
    {
    }

    /**
     * Test attribute "processing_hints"
     */
    public function testPropertyProcessingHints()
    {
    }

    /**
     * Test attribute "processing_warnings"
     */
    public function testPropertyProcessingWarnings()
    {
    }

    /**
     * Test attribute "tag_suggestions"
     */
    public function testPropertyTagSuggestions()
    {
    }
}
