<?php
/**
 * VideoProcessingDetailsProcessingProgressTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * YouTube Data
 *
 * Supports core YouTube features, such as uploading videos, creating and managing playlists, searching for content, and much more.
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * VideoProcessingDetailsProcessingProgressTest Class Doc Comment
 *
 * @category    Class
 * @description Video processing progress and completion time estimate.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class VideoProcessingDetailsProcessingProgressTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "VideoProcessingDetailsProcessingProgress"
     */
    public function testVideoProcessingDetailsProcessingProgress()
    {
    }

    /**
     * Test attribute "parts_processed"
     */
    public function testPropertyPartsProcessed()
    {
    }

    /**
     * Test attribute "parts_total"
     */
    public function testPropertyPartsTotal()
    {
    }

    /**
     * Test attribute "time_left_ms"
     */
    public function testPropertyTimeLeftMs()
    {
    }
}
